package voyager

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	PlayerRouter
	PlayerProfileRouter
	PlayerExtendRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
